name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Inject secret into secret.js
        run: |
          echo "window.DISCORD_WEBHOOK_URL='${{ secrets.DISCORD_WEBHOOK }}';" > secret.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./build  # Adjust to your project's build directory
          publish_branch: gh-pages