name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Default GitHub token provided by GitHub Actions
          publish_dir: ./  # Adjust to your project directory
          publish_branch: gh-pages  # Adjust to your GitHub Pages branch

      - name: Inject secret into JS
        run: |
          echo "window.DISCORD_WEBHOOK_URL='${{ secrets.DISCORD_WEBHOOK_URL }}';" > secret.js
          cat secret.js rp_calculator.js > temp.js && mv temp.js rp_calculator.js
