name: Deploy to GitHub Pages and Send Feedback

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Inject secret into JS
        run: |
          echo "window.DISCORD_WEBHOOK_URL='${{ secrets.DISCORD_WEBHOOK_URL }}';" > secret.js
          cat secret.js rp_calculator.js > temp.js && mv temp.js rp_calculator.js
        working-directory: ${{ github.workspace }}

      - name: Build and Deploy to GitHub Pages
        run: |
          npm run build  # Adjust based on your build script
          npm run deploy  # Adjust based on your deploy script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for deploying to GitHub Pages

      - name: Send Feedback
        run: |
          node rp_calculator.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Discord webhook URL
