name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust to your main branch name or trigger branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Replace webhook URL
        run: sed -i "s|PLACEHOLDER_FOR_WEBHOOK_URL|${{ secrets.DISCORD_WEBHOOK_URL }}|" rp_calculator.js

      - name: Deploy to temporary branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: .  # Adjust if your build output is in a different directory
          publish_branch: gh-pages  # Use a temporary branch name

      - name: Update main branch
        run: |
          git checkout main
          git pull
          git merge gh-pages --no-commit --no-ff
          git commit -m "Update main branch with deployment changes"
          git push origin main
