name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust to your main branch name or trigger branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Replace webhook URL
        run: |
          node -e "const fs = require('fs'); let content = fs.readFileSync('rp_calculator.js', 'utf8'); content = content.replace('PLACEHOLDER_FOR_WEBHOOK_URL', '${{ secrets.DISCORD_WEBHOOK_URL }}'); fs.writeFileSync('rp_calculator.js', content);"      

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: .  # Adjust if your build output is in a different directory
          publish_branch: gh-pages  # Change this to your deployment branch (e.g., gh-pages)