name: Secrets and env variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      - name: tell secret
        run: echo "testing thingy ${{secrets.DISCORD_WEBHOOK}}"

      - uses: action/checkout@v2